server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification_service_db?useSSL=false&serverTimezone=UTC
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update   # أول مرة ممكن create، وبعدها رجّعها update
    show-sql: true
