server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification_service_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ""   # لو عندك كلمة مرور، عيّنها هنا
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # أحد الخيارين التاليين يكفي. جرّب الأول:
    database-platform: org.hibernate.dialect.MySQLDialect
    # أو (بديل مكافئ):
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,mappings
