server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_service_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update   # جرّب create أول تشغيل لو بدك تجبر الإنشاء
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate.SQL: debug
logging.level.org.hibernate.orm.jdbc.bind: trace
